# Generated by Django 4.2.10 on 2024-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('street_adddress', models.CharField(max_length=80)),
                ('job_description', models.CharField(max_length=80)),
            ],
        ),
    ]
