# Generated by Django 4.2.10 on 2024-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_job_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsLetterSubscriberModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=80, unique=True)),
            ],
        ),
    ]
